- name: Delete Server Profile OneView w/ Synergy
  hosts: localhost
  connection: local
  gather_facts: false

  environment:

  vars:
    oneview_config: "/usr/local/etc/oneview/oneview_config.json"
    ansible_python_interpreter: "/usr/local/bin/python"
    synergy_profile_name: "RHEL_Ansible_Test"
    synergy_hardware_name: "SynergyFrame01, bay 4"

  tasks:
    - name: Power-Off the server
      oneview_server_hardware:
        config: "{{ oneview_config }}"
        state: power_state_set
        data:
          name : "{{ synergy_hardware_name }}"
          powerStateData:
            powerState: "Off"
            powerControl: "MomentaryPress"

    - name: Ensure that the Deployment Server is absent
      oneview_server_profile:
        config: "{{ oneview_config }}"
        state: absent
        data:
          name: "{{ synergy_profile_name }}"

