- name: Install Apache httpd
  hosts: all
  become: yes

  environment:

  vars:

  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Configure httpd
      copy:
        src: httpd.conf
        dest: /etc/httpd/conf/httpd.conf
        owner: root
        group: root
        mode: 0644
      when: ansible_os_family == "RedHat"

    - name: Start Apache httpd service
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"
