- name: Configure MariaDB Server
  hosts: all
  become: yes

  environment:

  vars:

  tasks:
    - name: Configure mariadb
      copy:
        src: my.cnf
        dest: /etc/my.cnf
        owner: root
        group: root
        mode: 0644
      register: my_cnf
      when: ansible_os_family == "RedHat"

    - name: Restart MariaDB server
      service:
        name: mariadb
        state: restarted
      when:
        - ansible_os_family == "RedHat"
        - my_cnf | changed
