- name: Create Database MariaDB Server
  hosts: all
  become: yes

  environment:

  vars:

  tasks:
    - name: Check variables
      fail:
      when:
        - db_name is defined

    - name: Create database
      mysql_db:
        name: "{{ db_name }}"
        state: present
